# Generated by Django 4.2 on 2023-04-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Question_text',
            new_name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='new_field',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
