# Generated by Django 4.2 on 2023-04-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_question_text_question_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='new_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
