# Generated by Django 4.2 on 2023-04-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_new_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='new_name',
        ),
    ]
